### ISSUE TITLE
Update to next fractal-tasks-core version (with support for enum arguments)

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-tasks-template#10]
See https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/745#issuecomment-2154392329.

In general, we should always bump the fractal-tasks-core version whenever there are updates that are not in the `tasks` subpackage (i.e., work on the core library or dev tools).

**Comment by jluethi** [comment]
Done with #11
