### ISSUE TITLE
Introduce new tasks metadata

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-tasks-template#17]
Requires fractal-tasks-core 1.3.3, examples in https://github.com/fractal-analytics-platform/fractal-tasks-core/pull/855.

1. For `authors`, we could maybe re-use the one which is set in pyproject.toml through copier?
2. For `category`, `modality` and `tags` we should show where they should be set.

**Comment by lorenzocerrone** [comment]
This pull request partially resolves this issue https://github.com/fractal-analytics-platform/fractal-tasks-template/pull/18

But from what I can see the author field is not yet exposed in tasks-core:
https://github.com/fractal-analytics-platform/fractal-tasks-core/blob/9e4efc455ca1c2b9867a8dae6b024b1733a8464d/fractal_tasks_core/dev/task_models.py#L25C1-L38C1

Am I getting it wrong? @tcompa
