### ISSUE TITLE
Example task not working with fractal-tasks-core 0.14.0

### ISSUE THREAD

**Issue by fstur** [fractal-analytics-platform/fractal-tasks-template#4]
Some fractal-tasks-core functions that are imported in the example task 'thresholding_task.py' are no longer available in fractal-tasks-core 0.14.0:

from fractal_tasks_core.lib_ngff import load_NgffImageMeta
from fractal_tasks_core.lib_pyramid_creation import build_pyramid

**Comment by jluethi** [comment]
Ok, turns out it was just those 2 :)

As you can see, the actual example Fractal task is very barebones, we definitely want to add more. But we'll do so after an upcoming task API refactor
